In [1]:
import numpy as np

In [3]:
revenue_usa = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenue_usa

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [4]:
revenue_ind = np.dot(revenue_usa,75)
revenue_ind

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [22]:
unit_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])

In [23]:
unit_sold

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [24]:
price_per_unit

array([20, 30, 15])

In [28]:
total_sales = np.dot(price_per_unit,unit_sold)

In [29]:
total_sales

array([1900, 2640, 1430])

In [30]:
(50*20)+(10*30)+(40*15)

1900